[package]
name = "dither_some"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.40", features = ["derive"] }

[dev-dependencies]
criterion = "0.5"

[[bench]]
name = "frame_benchmark"
harness = false

[[bench]]
name = "dither_benchmark"
harness = false